FROM ubuntu:latest

RUN apt-get update && apt-get install -y build-essential automake1.11 autoconf libevent-dev libseccomp-dev git

ADD . /src

CMD cd /src && ./autogen.sh && ./configure --enable-seccomp && make -j && ./testapp
