FROM archlinux/base:latest

ARG CONFIGURE_OPTS="--enable-seccomp"

RUN pacman -Sy && pacman --noconfirm -S gcc automake autoconf libevent libseccomp git make perl
RUN ln -s /usr/bin/core_perl/prove /usr/bin/prove

ADD . /src
WORKDIR /src

RUN aclocal
RUN autoheader
RUN automake --gnu --add-missing
RUN autoconf

RUN ./configure ${CONFIGURE_OPTS}
RUN make -j

CMD make test
