FROM ubuntu:latest

ARG CONFIGURE_OPTS="--enable-seccomp"

RUN apt-get update && apt-get install -y --no-install-recommends build-essential automake autoconf libevent-dev libseccomp-dev git pkg-config && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash memcached
ADD . /src
WORKDIR /src

RUN ./autogen.sh
RUN ./configure ${CONFIGURE_OPTS}
RUN make -j

USER memcached

CMD make test
