FROM ubuntu:latest

ARG CONFIGURE_OPTS="--enable-seccomp"

RUN apt-get update && apt-get install -y build-essential automake1.11 autoconf libevent-dev libseccomp-dev git

ADD . /src
WORKDIR /src

RUN ./autogen.sh
RUN ./configure ${CONFIGURE_OPTS}
RUN make -j

CMD make test
